const weatherTypes = Object.freeze({
  GROUP_WEATHER: 'GROUP_WEATHER',
  SEARCH_WEATHER: 'SEARCH_WEATHER',
  DETAIL_WEATHER: 'DETAIL_WEATHER',
  CLEAR_WEATHER: 'CLEAR_WEATHER',
  HOURLY_WEATHER: 'HOURLY_WEATHER',
  NO_WEATHER: 'NO_WEATHER'
});

export default weatherTypes;
